# jenkins sets this to warn by default
loglevel: info
strictPeerDependencies: false
lockfileIncludeTarballUrl: false

packages:
  - ./*
catalogs:
  a12Libs:
    "@com.mgmtp.a12.base/base-model-api": "^29.3.0"
    "@com.mgmtp.a12.client/client-core": "^16.2.1"
    "@com.mgmtp.a12.client/client-application-model-migration": "^16.2.1"
    "@com.mgmtp.a12.crud/crud-core": "^2.3.0"
    "@com.mgmtp.a12.dataservices/dataservices-access": "^38.4.0"
    "@com.mgmtp.a12.expression/expression-core": "^2.0.6"
    "@com.mgmtp.a12.formengine/formengine-core": "^38.4.0"
    "@com.mgmtp.a12.formengine/formengine-model-migration": "^38.4.0"
    "@com.mgmtp.a12.kernel/kernel-core-runtime-api-ts": "^30.8.1"
    "@com.mgmtp.a12.kernel/kernel-md-facade": "^30.8.1"
    "@com.mgmtp.a12.overviewengine/overviewengine-core": "^38.3.0"
    "@com.mgmtp.a12.overviewengine/overviewengine-model-migration": "^38.3.0"
    "@com.mgmtp.a12.migrationtool/migrationtool-utils": "^2.1.1"
    "@com.mgmtp.a12.migrationtool/migrationtool-core": "^2.1.1"
    "@com.mgmtp.a12.relationshipengine/relationshipengine-core": "^2.3.0"
    "@com.mgmtp.a12.utils/utils-collections": "^6.2.0"
    "@com.mgmtp.a12.utils/utils-connector": "^8.2.1"
    "@com.mgmtp.a12.utils/utils-localization": "^7.2.0"
    "@com.mgmtp.a12.utils/utils-localization-react": "^7.2.0"
    "@com.mgmtp.a12.utils/utils-logging": "^6.2.0"
    "@com.mgmtp.a12.widgets/widgets-core": "^38.3.0"
  libs:
    "@types/react": "^19.0.10"
    "@types/react-dom": "^19.0.4"
    "@types/react-test-renderer": "^19.0.0"
    "@types/react-redux": "^7.1.34"
    "dayjs": "^1.11.13"
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "react-test-renderer": "^19.0.0"
    "react-redux": "^7.2.1"
    "redux": "^4.2.1"
    "redux-saga": "^1.1.3"
    "react-dnd": "^16.0.0"
    "styled-components": "^6.1.18"
    "typed-redux-saga": "^1.3.1"
    "typescript": "5.8.2"
    "typescript-fsa": "^3.0.0"
  devLibs:
    "@com.mgmtp.a12.devtools/eslint-config": "^3.1.0"
    "@com.mgmtp.a12.devtools/prettier-config": "^1.1.0"
    "@com.mgmtp.a12.devtools/tsconfig": "^1.1.0"
    "@types/mochawesome": "^6.2.4"
    "@types/node": "^22.15.0"
    "@vitest/coverage-v8": "^4.0.17"
    "mocha": "^11.7.5"
    "mocha-junit-reporter": "^2.2.1"
    "mocha-multi-reporters": "^1.5.1"
    "mochawesome": "^7.1.3"
    "mochawesome-merge": "^4.3.0"
    "mochawesome-report-generator": "^6.2.0"
    "rimraf": "^6.0.1"
    "ts-node": "^10.9.2"
    "vitest": "^4.0.17"
