server.port=15001

# Profiles
spring.profiles.active=dataservices-actuators,dataservices-rpc,dataservices-embedded_postgres,contentstore-embedded_postgres,dataservices-embedded_contentstore,dataservices-uaa,dataservices-cdd_async
# Database
spring.datasources.dataservices.embedded-postgres.path=file:${DB_TEMP_DIR}/db/ds-embedded-postgres
spring.datasources.dataservices.embedded-postgres.port=15434
spring.datasources.contentstore.embedded-postgres.path=file:${DB_TEMP_DIR}/db/cs-embedded-postgres

# Data (import)
mgmtp.a12.dataservices.initialization.import.models.path=classpath:/models

# Attachment
mgmtp.a12.dataservices.attachments.enabled=true
mgmtp.a12.dataservices.attachments.rest-endpoint.enabled=true
mgmtp.a12.dataservices.attachments.thumbnail.preview.enabled=true
mgmtp.a12.dataservices.contentstore.server.api.enabled=true
mgmtp.a12.dataservices.contentstore.base-url=./
# Authentication
mgmtp.a12.uaa.authentication.types=ANONYMOUS
mgmtp.a12.uaa.authentication.context-path=/api
mgmtp.a12.uaa.authentication.cors.allowedOrigins=*
mgmtp.a12.uaa.authentication.principal.access-rights-resource=classpath:/roles.yaml
mgmtp.a12.uaa.authentication.anonymous.access.urls=/api/**
mgmtp.a12.uaa.authentication.anonymous.roles=anonymous

# Actuator
management.endpoint.health.showDetails=always

# Increase maximum page size per query request
mgmtp.a12.dataservices.query.page-request.page-size-limit=1000

# Query API
mgmtp.a12.dataservices.query.reindexing.mode=REBUILD_INDEX

# Increase maximum RPC calls per request, use to seed/clean data
mgmtp.a12.dataservices.json-rpc.max-method-calls-per-request=9999
