[versions]
# A12 components
base = "29.3.2"
kernel = "30.8.6"
dataservices = "38.4.5"
build-utilities = "0.5.0"
integration = "0.1.6"
# Gradle plugins
spring-boot = "3.4.1"
node-gradle = "7.0.1"
docker-remote-api = "9.3.7"
devtools-deployment = "0.8.1"
git-version = "3.0.0"
artifact-publish = "0.4.3"
thirdPartyNoticesPlugin = "0.2.25"
spotless = "7.0.2"
# Other libraries
logstash = "7.4"
logback-classic = "1.5.6"
lombok = "1.18.30"

[libraries]
# A12
build-utilities = { module = "com.mgmtp.a12.devtools.plugins:build-utilities", version.ref = "build-utilities" }
base-bom = { module = "com.mgmtp.a12.base:base-bom", version.ref = "base" }
kernel-bom = { module = "com.mgmtp.a12.kernel:kernel-bom", version.ref = "kernel" }
dataservices-bom = { module = "com.mgmtp.a12.dataservices:dataservices-parent", version.ref = "dataservices" }
dataservices-server-app = { module = "com.mgmtp.a12.dataservices:dataservices-server-app", version.ref = "dataservices" }
dataservices-server-init-app = { module = "com.mgmtp.a12.dataservices:dataservices-server-init-app", version.ref = "dataservices" }
# Other
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "spring-boot" }
logstash = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[plugins]
git-version = { id = "com.palantir.git-version", version.ref = "git-version" }
artifact-publish = { id = "com.mgmtp.a12.bd.artifact-publish", version.ref = "artifact-publish" }
integration = { id = "com.mgmtp.a12.devtools.plugins.integration", version.ref = "integration" }
devtools-deployment = { id = "com.mgmtp.a12.devtools.plugins.deployment", version.ref = "devtools-deployment" }
devtools-thirdPartyNotices = { id = "com.mgmtp.a12.devtools.plugins.third-party-notices", version.ref = "thirdPartyNoticesPlugin" }
docker-remote-api = { id = "com.bmuschko.docker-remote-api", version.ref = "docker-remote-api" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "node-gradle" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
