////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
[#prerequisite]
=== Prerequisite

[#prerequisite/client]
==== Client

Basic knowledge of using Client is necessary because Tree Engine heavily depends on Client.
See link:/docs/OVERALL/dev_tutorial_frontend_intro/index.html[Frontend tutorial] for further details.

For technical requirements, Tree Engine shared the same configuration as Client.
If Client has been running, Tree Engine should be able to use.

Please refer to the full-stack-project-template repository for an up-to-date template.

[#prerequisite/relationship]
==== Relationship

Tree Engine only works if there is at least a relationship between entities. Otherwise, Overview Engine can serve well.
Having knowledge about how relationship works in A12 ecosystem is a *must*.

[#prerequisite/sme]
==== Simple Model Editor (SME)

SME is a tool that allows managing all models in A12 ecosystem.
See link:/docs/SME/sme-ba-docs/index.html[SME documentation] for further details.

Every A12 component will come with an ability to manage business requirements via a model.
Tree Engine is not an exception in which SME is utilized to manage link:/docs/SME/sme-tm-ba-docs/index.html[Tree Model].
