////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
[#installation]
=== Installation

Tree Engine is provided as a npm package containing ES5 CommonJS modules. Run the following command to install Tree Engine:

[source]
----
npm install @com.mgmtp.a12.treeengine/treeengine-core
----

WARNING: It is assumed that the project is bootstrapped with <<prerequisite/client, Client>>.

After that, it is possible to start integrating Tree Engine into the application.

==== Register Tree Engine modules

The registration process of Tree Engine is quite simple, it is only required to register two Tree Engine modules (link:./assets/generated/typedoc/modules/extensions_client.TreeEngineFactories.html[TreeEngineFactories] and link:./typedoc/modules/extensions_server_connector.TreeEngineServerConnectorFactories.html[TreeEngineServerConnectorFactories]).

[source,typescript,options="nowrap",title="src/appsetup.ts"]
--
import { TreeEngineFactories } from "@com.mgmtp.a12.treeengine/treeengine-core/lib/extensions/client";
import { TreeEngineServerConnectorFactories } from "@com.mgmtp.a12.treeengine/treeengine-core/lib/extensions/server-connector";

export function setup() {
  ModuleRegistryProvider.getInstance().addModule(TreeEngineFactories.createModule());
  ModuleRegistryProvider.getInstance().addModule(TreeEngineServerConnectorFactories.createModule());

  return ApplicationFactories.createApplicationSetup({ ... })
}
--

CAUTION: See link:/docs/CLIENT/client-documentation-bundle/index.html#_moduleregistry[Module Registry] for further information about registering modules in a Client application.

==== Register Tree Engine in non-modular way

However, in case tree engine modules are not a preferable way to setup the application, TreeEngine's factories also allow registering in a non-modular way as below:

NOTE: Look for "Tree Engine" comment to find out which part of the createApplicationSetup to register the Tree Engine

WARNING: In general, only Tree Engine's data providers needed to be placed above Form Engine's data provider. For the rest of the registration
(data reducers, middlewares, sagas, view component), the order does not matter.

[source,typescript,options="nowrap",title="src/appsetup.ts"]
--
export function setup() {
  ...
include::assets/generated/typescript/showcase/appsetup.ts[tags="SetupTreeEngine"]

  return config;
}
--

[#installation/register-container-factory]
==== Register Container Factory

There are three ways to register the Tree Engine renderer:

===== Default Module

The default module, shipped by link:./assets/generated/typedoc/functions/extensions_client.TreeEngineFactories.createModule.html[TreeEngineFactories.createModule()], provides the default one, named `TreeEngine`.
It should work by following registration steps for a standard link:/docs/CLIENT/client-documentation-bundle/index.html#_modularization[Client module].

===== Default ViewComponentProvider

In case of not using TreeEngine's module, it is possible to include Tree Engine's view component provider

[source,typescript,options="nowrap",title="src/defaultContainerFactory.tsx"]
--
import { TreeEngineFactories } from "@com.mgmtp.a12.treeengine/treeengine-core/lib/extensions/client";

function viewComponentProvider(componentName: string) {
  return TreeEngineFactories.viewComponentProvider(componentName);
}
--

This provider also provides Tree Engine view component named `TreeEngine`, which will be available to be used in the <<application-model,Application Model>>.

===== Customized ViewComponentProvider

This approach will allow more flexibility, it is possible to not only change container's name but also injecting customized configuration props to the view, even able to replace Tree Engine View component with a different one:

[source,typescript,options="nowrap",title="src/customContainerFactory.tsx"]
--
include::assets/typescript/features/crudViewProvider.tsx[tags="SetupViewProvider"]
--

[#installation/drag-and-drop-provider]
==== Drag and Drop Provider

Since version 7.0.0, link:#view-customization/component-map[ComponentMap] no longer supports DndProvider.
Therefore, if the Tree Engine requires any drag & drop functionality (enabled by default via tree model),
it is mandatory to have a DndProvider registered as the highest order component as follow:

[source,typescript,options="nowrap",title="src/app/page/index.tsx"]
----
import { DndProvider } from "react-dnd";
import { DragAndDropUtils } from "@com.mgmtp.a12.widgets/widgets-core/lib/common";

export const BasePage = () => (
  <DndProvider
    backend={DragAndDropUtils.DefaultDndBackend}
    options={DragAndDropUtils.DefaultDndBackendOptions}
  >
    <LocalizerContext.Provider value={{ locale, dataFormats, localizer, conversion }}>
      ...
    </LocalizerContext.Provider>
  </DndProvider>
);
----

==== Enable JSON-RPC

https://www.jsonrpc.org/[JSON-RPC] is a standard that can be used to replace batch endpoint and expose methods to be called via network in a more standardized way.
JSON-RPC provides a schema for the request, response and description of standardized error messages.

Tree Engine uses it to establish the connection to A12 Data Services.
Therefore, please ensure JSON-RPC is enabled by having `mgmtp.a12.dataservices.jsonRpc.enabled=true` property which configured on link:/docs/DATA_SERVICES/dataservices-documentation-src/index.html#Other-initialization-properties[A12 Data Services properties].
