////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
[#localization]
=== Localization

An application using Tree Engine has to provide a `LocalizerContext` instance from `utils-localization-react` package.
The context can be initialized by using `DefaultLocalizerContextProvider`, or customized completely by passing
three parameters: `localizer`, `locale`, and `dataFormats` into `LocalizerContext`. `localizer` receives an array of `Localizables` and returns resolved
string according to the current `locale`. For more details, see link:/docs/utils_localization/utils-localization-documentation-bundle/index.html[Utils localization documentation].

NOTE: By default, Tree Engine only provides texts for two locales: `en` and `de`.
For other locales, they can be defined via models or a customized `localizer`.

==== API

Tree Engine offers two alternative localization approaches:

* In which the React hooks are available, link:./assets/generated/typedoc/modules/core_services_localization.LocalizerHooks.html[LocalizerHooks] namespace with five different hooks can be used:
** *useLocalizedResource*: to translate Tree Engine resources via public `RESOURCE_KEYS`.
** *useLocalizedTreeElement*: to translate localized texts in Tree Model's elements.
** *useLocalizedEnumerationValue*: to translate labels of `EnumerationType` values.
** *useLocalizedBooleanValue*: to translate labels of `BooleanType` values.
** *useLocalizedConfirmValue:* to translate labels of `ConfirmType` values.

* In which the React hooks are not available, `LocalizableFactory` namespace with alternative functions can be used to create
corresponding localizables.

==== Keys

Every localizable element in Tree Engine is identified by a key. The keys can be categorized into the static resource keys and model element keys.

===== Static Resource Keys

Resources such as titles for notifications and confirmation buttons are marked using static keys.
The static keys are defined and well-documented in `RESOURCE_KEYS` in `core/services/localization/internal/languages/keys.ts`.
Please see the file for more details.

===== Model Element Keys

The keys for elements rendered based on models such as buttons and column header labels are dynamically generated.
The schemas for the keys are as follows:

[%header,cols="1,3"]
|===
|Element                          |Key
|Table header label/Aria label   a|`uiModel.{tree-model-name}.header.labels`
|Column header label             a|`uiModel.{tree-model-name}.columns.{column-id}`
|Sub-header button               a|`uiModel.{tree-model-name}.subHeaderBox.buttons.(label\|title).{button-id}`
|Footer button                   a|`uiModel.{tree-model-name}.footerBox.buttons.(label\|title).{button-id}`
|Node event row action           a|`uiModel.{tree-model-name}.nodes.{node-id}.actions.event.{event-name}.(label\|title)`
|Node insert row action          a|`uiModel.{tree-model-name}.nodes.{node-id}.actions.insert.(label\|title)`
|Node event context menu action  a|`uiModel.{tree-model-name}.nodes.{node-id}.contextMenu.event.{event-name}.(label\|title)`
|Node insert context menu action a|`uiModel.{tree-model-name}.nodes.{node-id}.contextMenu.insert.(label\|title)`
|Context menu group title        a|`uiModel.{tree-model-name}.nodes.{node-id}.contextMenu.groups.{group-name}.title`
|Confirmation dialog             a|`uiModel.{tree-model-name}.nodes.actions.event.confirmation.{event-name}`
|Enumeration values              a|`documentModel.enumValue.{document-model-name}.{...element-path}.{enumeration-field-value}`
|Boolean values                  a|`documentModel.boolean.{document-model-name}.{...element-path}.(true\|false)`
|                                a|`RESOURCE_KEYS.(true\|false)`
|Confirm values                  a|`documentModel.confirm.{document-model-name}.{...element-path}.(true\|null)`
|                                a|`RESOURCE_KEYS.(true\|null)`
|===

