////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
[#advanced]
== Advanced

In this section, we will focus on some more advanced customizations available in Tree Engine.

include::0401_root_node_customization.adoc[]

include::0402_disable_link_creation_in_tree_engine.adoc[]

include::0403_custom_new_link_position.adoc[]

include::0404_preload_child_nodes.adoc[]

include::0405_unregister_default_sagas.adoc[]

include::0406_register_custom_actions_for_saga_initialization.adoc[]

include::0407_maximum_amount_of_root_nodes.adoc[]

include::0408_custom_initial_expansion.adoc[]

include::0499_wdyr.adoc[]
