////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
[#advanced/new-link-position]
=== Custom New Link Position

By default, A12 Data Services controls the order of the newly added nodes.
However, developers can change this behavior by providing the following setting to the Server Connector module.

[source,typescript,options="nowrap",title="src/appsetup.ts"]
--
import { Relationship } from "@com.mgmtp.a12.dataservices/dataservices-access/lib";

function setup() {
  const settings: TreeEngineServerConnectorFactories.ModuleSettings = {
    addLinkSetting: { newLinkPosition: Relationship.LinkPosition.BOTTOM }
  };

  ModuleRegistryProvider.getInstance().addModule(TreeEngineServerConnectorFactories.createModule(settings));
}
--

`newLinkPosition` field accepts any value of `Relationship.LinkPosition` enumeration, `undefined` or a function which returns those values.
The function receives following parameters:

* `activityId`: The current Tree Engine activity ID.
* `relationshipName`: The relationship name of the new link is about to be created.

By returning `undefined`, the Engine will fall back to the default behavior.

NOTE: This setting will not affect the relationship models which do not have ordering enabled.
