////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
[#advanced/preload-child-nodes]
=== Child Nodes Preloading

By default, Tree Engine always shows the arrow buttons besides the nodes which can be parental.
This behavior could cause the end users expand the leaf nodes unnecessarily. With this feature,
the arrow buttons will only be shown if their corresponding nodes really have one or more children.

In the Server Connector module's setting, `preloadChildNodes` field can accept `boolean` values, or `undefined`,
or a function that returns those values.

WARNING: In order to determine whether the target node has any children or not, Tree Engine needs to fetch all data of child nodes including their documents,
instead of the number of children merely. This limitation of Data Services could affect the bandwidths requests/responses to/from the server. Therefore, this feature should be used wisely and in concern.

[source,typescript,options="nowrap",title="src/appsetup.ts"]
--
import { ModuleRegistryProvider } from "@com.mgmtp.a12.client/client-core/lib/core/application";
import { TreeEngineServerConnectorFactories } from "@com.mgmtp.a12.treeengine/treeengine-core/lib/extensions/server-connector";

function setup() {
  const settings: TreeEngineServerConnectorFactories.ModuleSettings = {
    preloadChildNodes: true
  };

  ModuleRegistryProvider.getInstance().addModule(TreeEngineServerConnectorFactories.createModule(settings));
}
--

