////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
[#advanced/register-custom-actions-for-saga-initialization]
=== Register Custom Actions for Saga Initialization

By default, Tree Engine matches one of these actions to trigger Tree Engine's initialization of its sagas: `ActivityActions.push`,
`ActivityActions.cancel` and `ActivityActions.commit.done`. These sagas are used in every interaction in the engine.
Therefore, in case of having customization built on top of Client that does not use one of these actions to create/re-create an activity, the specification of action to `TreeEngineFactories.SagaSetting` is necessary as below:

[source,typescript,options="nowrap",title="src/appsetup.ts"]
--

export function setup() {
    const treeEngineModuleSetting: TreeEngineFactories.ModuleSettings = {
            sagaSetting: { sagaInitializationMatchers: [yourActionCreator] }
    };

    ModuleRegistryProvider.getInstance().addModule(TreeEngineFactories.createModule(treeEngineModuleSetting));
  ...
}

--
