////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
[#advanced/maximum-amount-of-nodes]
==== Maximum Number of Nodes

Query API request from Data Services comes with a default maximum page size limit of 100, Tree Engine respects the limit and use it as the default maximum page size limit per Query request.

For the level by level expansion strategy, this maximum number will affect the amount of root nodes, or the amount of child nodes from a parent node.

For the tree expansion strategy, this maximum number will only affect the amount of root nodes, the maximum amount of child nodes will remain unlimited.

In case of raising the limit, developer will not only have to set the `mgmtp.a12.dataservices.query.page-request.page-size-limit` but also required to update the default maximum page limit in the Tree Engine configuration.

[source,typescript,title="TreeEngineServerConnector"]
```
TreeEngineServerConnectorFactories.createModule({
    ...otherSettings,
    dataServicesSetting: {
        maximumPageSize: 200, // the value should match the one set in Data Services
    },
});
```
